# Generated by Django 6.0.4 on 2026-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_index',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en inicio'),
        ),
    ]
