# Generated by Django 6.0.4 on 2026-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0005_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
